---
- name: Build go-app docker image with the docker_image module
  hosts: localhost
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=go-app dest=/tmp
    - name: install the latest version of Apache
      yum:
        name: python-py
        state: latest
        
    - name: install docker-py
      pip:
        name: docker-py
        state: present
      
    - name: Log into DockerHub
      docker_login:
         username: motoskia
         password: motoskiaking

    - name: build the image
      docker_image:
         name: motoskia/go-app
         tag: latest
         path: /tmp/go-app
         state: present
         push: yes

    - name: run the site in a docker container
      docker_container:
         name: go-app
         image: motoskia/go-app:latest
         state: started
         restart: yes
         ports:
          - "8082:8082"
